<?php 
$path = "../";      // Siamo dentro una cartella, dobbiamo salire di un livello per trovare css e images
$page = "R&I";    // Questo farà illuminare "R&I" nel menu
include '../includes/header_en.php'; // Notare ../ prima di includes
?>
        <section class="inner-hero fade-in">
          <div class="breadcrumb"><a href="../index_en.php">Home</a> / <a href="ricerca-innovazione_en.php">Research and Innovation</a> / EmsoDEV</div>
          <h1 class="inner-title">EmsoDEV</h1>
        </section>

        <section class="content fade-in">
          <div class="iub_header">
            <p style="text-align: center;">
              <img src="../images/EMSODEV.png" alt="EMSODEV" class="wp-image-1868" style="width:400px"/>
            </p>
            <p style="text-align: justify;">
              Within the scope of activities related to the European project <strong>EMSODEV</strong>, funded by the European Commission under the <strong>Horizon 2020</strong> program, the scientific lead of Swing:It, together with their team, manages a consultancy entrusted by SpacEarth Technology Srl on the <strong>planning, design, and development of data management platforms</strong>, as stated in the project’s Description of Action (DoA). Specifically, the consultancy activities fall within WP6 “Data Management Platform and Related Services” and include the following tasks:
            </p>
            <ul>
              <li>Responsibility for “<strong>Task 6.1: Data Management Plan</strong>” and the drafting, submission, and review of “Deliverable 6.1: Data Management Plan”;</li>
              <li>Responsibility for “<strong>Task 6.2: Data management platform architecture design</strong>” and the drafting, submission, and review of “Deliverable 6.2: Data management platform architecture design”;</li>
              <li>Participation and contribution to “Task 6.3: Data management platform infrastructure setup and implementation”;</li>
              <li>Participation and contribution to “Task 6.4: Data management platform tools”;</li>
              <li>Participation and contribution to “Task 6.5: Interoperability with existing EMSO local data nodes”;</li>
              <li>Training and supervision of INGV and SpacEarth Technology staff with less experience involved in project “Data management” activities;</li>
              <li>Contribution to the dissemination and communication of WP6 results;</li>
            </ul>
            <p style="text-align: justify;">
              The outcomes of these activities will enable the entire community to access and exploit the data generated by EGIM (EMSO Generic Instrumentation Module), the advanced seabed and water column monitoring module that will be produced by the project.
            </p>
          </div>
        </section>
<?php include '../includes/footer_en.php'; ?>
