<?php 
$path = "../";      // Siamo dentro una cartella, dobbiamo salire di un livello per trovare css e images
$page = "forschung";    // Questo farà illuminare "R&E" nel menu
include '../includes/header_de.php'; // Notare ../ prima di includes
?>
        <section class="inner-hero fade-in">
          <div class="breadcrumb"><a href="../index_de.php">Home</a> / <a href="ricerca-innovazione_de.php">Forschung und Innovation</a> / 3DLAB Sicilia</div>
          <h1 class="inner-title">3DLAB Sicilia</h1>
        </section>

        <section class="content fade-in">
          <div class="iub_header">
            <p style="text-align: center;"><img src="../images/3DLAB.png" alt="3DLAB" class="wp-image-1868" style="width:400px"/></p>
            <p style="text-align: justify;">Im Rahmen des P.O. FESR SICILIA 2014/2020, Thematisches Ziel 1 – Forschung, technologische Entwicklung und Innovation; Spezifisches Ziel 1.1 – Steigerung der Innovationsaktivitäten der Unternehmen; Maßnahme 1.1.5 – Unterstützung des technologischen Fortschritts der Unternehmen durch die Finanzierung von Pilotlinien sowie von Maßnahmen zur frühen Produktvalidierung und zur großskaligen Demonstration, wurde das Progetto 3DLab – Sicilia – Aufbau eines regionalen Netzwerks zur Bereitstellung innovativer Dienstleistungen auf der Grundlage fortschrittlicher Visualisierungstechnologien finanziert.</p>
            <p style="text-align: justify;">Die Verfügbarkeit, immer steigend und immer kostengünstiger, einerseits von 3D-Scannern, ausgeklügelten Fotogrammetrie-Systemen und Softwareumgebungen mit immer mehr Funktionen und andererseits von stationären Geräten und tragbaren Geräten zur Nutzung immersiver Umgebungen, hat die Schaffung eines echten Marktes für Virtual Reality (VR) und Augmented Reality (AR) ermöglicht. Laut dem Worldwide Semiannual Augmented and Virtual Reality Spending Guide von IDC wird der globale Umsatz und die Ausgaben für AR und VR mit sehr hohen jährlichen Wachstumsraten prognostiziert und soll in wenigen Jahren über 150 Milliarden Dollar überschreiten. VR-Anwendungen werden immer häufiger und in vielen Bereichen eingesetzt, wie Medizin, Biologie, Automotive, Produktion, Kulturgüter, öffentliche Verwaltung, „Internet der Dinge“, Architektur, Gaming, Werbung, Online-Verkauf, Kommunikation und Marketing, Tourismus, Verlagswesen, Mode, Bildung, Training usw. Die Integration von VR in Geschäftsprozesse wie Design, Produktion, Simulation, Wartung, Sicherheit usw. ist äußerst bedeutend. Aus diesem Grund ist es nicht verwunderlich, dass (i) Laboratorien für VR/AR und fortgeschrittene Visualisierung kontinuierlich entstehen und sich sowohl im akademischen als auch im industriellen Umfeld weiterentwickeln, oft mit öffentlich-privater Kooperation, und (ii) die Europäische Kommission kürzlich das Projekt VISIONAIR finanziert hat, das erfolgreich eine kontinentale Netzwerkstruktur mit über 20 VR- und 3D-Visualisierungszentren aufgebaut und validiert hat, mit etwa 200 Anwendungen und Projekten aus Kulturgütern, Biologie, Chemie, Ingenieurwesen, Mechatronik, Medizin, industrieller Produktion und vielem mehr, die durch Wettbewerbsverfahren ausgewählt wurden.</p>
            <p style="text-align: justify;">3DLab-Sicilia zielt darauf ab, einerseits eine nachhaltige regionale Netzwerkstruktur aus drei (3) Zentren für VR/AR und 3D-Visualisierung zu schaffen und weiterzuentwickeln und andererseits diese zu validieren und zu fördern: eines in der Provinz Catania (bei SWING:IT), eines in Troina (EN, bei IRCCS-OASI) und eines in Palermo (bei IEMEST). Dieses Netzwerk, das nach unserem Wissen das erste seiner Art in Sizilien wäre, trägt den konventionellen Namen „Infrastruktur 3DLab-Sicilia“. Das Projekt validiert und demonstriert die Ausrüstung und Dienstleistungen der Infrastruktur mit einer Reihe von „Use Cases“ (einige bereits in der Vorbereitungsphase des Projekts identifiziert und andere während des Projekts durch Wettbewerbsverfahren ausgewählt), die die Themen der Smart Specialisation Strategy (S3) der Region Sizilien abdecken und deren Anwendungen und Produkte nach Projektende auf den Markt gebracht und Gewinn generieren können. Weitere Ziele von 3DLab-Sicilia sind die Verknüpfung der Infrastruktur mit der von VISIONAIR, um internationale Märkte zu schaffen, sowie die Definition des Management-, Geschäfts- und Nachhaltigkeitsmodells der Infrastruktur nach Projektende. Ein zentrales Element des Arbeitsplans von 3DLab-Sicilia, das die Konzepte von Open Innovation und Open Innovation 2.0 mit Dreifach- und „Vierfach-Helix“ vollständig unterstützt, ist die Schaffung eines Dienstes innerhalb der Infrastruktur, der das Konzept des „Liquid Lab“ übernimmt. „Liquid Labs“ (im industriellen Bereich als „Liquid Studios“ bekannt) sind sowohl reale als auch virtuelle Umgebungen, die innovative ICT-Dienste und -Lösungen nutzen, um Unternehmen zu helfen, ihren Innovationsprozess zu beschleunigen und ihre Ideen schnell in konkrete Anwendungen und Dienstleistungen umzuwandeln, mit dem Einsatz innovativer Technologien, intelligenter Automatisierung und neuer Softwareentwicklungsmethoden. Das „Liquid Lab“ von 3DLab-Sicilia ist so konzipiert und implementiert, dass (i) die schnelle Entwicklung von Anwendungen mit VR/AR und 3D-Visualisierung ermöglicht wird und (ii) Unterstützung rund um die Uhr für alle Akteure der „Vierfach-Helix“ der Innovation geboten wird. Themenbereich der regionalen Innovationsstrategie für die Spezialisierung S3 und verwendete Technologie: „Smart Cities & Communities“, insbesondere im Teilbereich „Smart Economy“.</p>
            <p style="text-align: justify;">Das Projektvolumen beträgt €3.996.985,59; die Förderung beträgt €3.567.561,18.</p>
            <p style="text-align: center;"><img src="../images/Gruppo-dei-loghi-Negativo-Colori.png" alt="Gruppo-dei-loghi-Negativo-Colori" class="wp-image-1868" style="width:400px"/></p>
          </div>
        </section>
<?php include '../includes/footer_de.php'; ?>
