<?php 
$path = "../";      // Siamo dentro una cartella, dobbiamo salire di un livello per trovare css e images
$page = "F&E";    // Questo farà illuminare "R&E" nel menu
include '../includes/header_de.php'; // Notare ../ prima di includes
?>
        <section class="inner-hero fade-in">
          <div class="breadcrumb"><a href="../index_de.php">Home</a> / <a href="ricerca-innovazione_de.php">Forschung & Innovation</a> / SECESTA ViaSafe</div>
          <h1 class="inner-title">SECESTA ViaSafe</h1>
        </section>

        <section class="content fade-in">
          <div class="iub_header">
            <p style="text-align: center;"><img src="../images/SECESTA.png" alt="SECESTA" class="wp-image-1868" style="width:400px"/></p>
            <p style="text-align: justify;">Im Rahmen des <strong>P.O. FESR SICILIA 2014/2020</strong>, <strong>Thematisches Ziel 1 – </strong>Forschung, Technologische Entwicklung und Innovation <strong>Spezifisches Ziel 1.1 </strong>- Steigerung der Innovationsaktivitäten von Unternehmen, <strong>Aktion 1.1.5 </strong>- Unterstützung der technologischen Weiterentwicklung von Unternehmen durch die Finanzierung von Pilotlinien und Maßnahmen zur frühen Validierung von Produkten und großflächigen Demonstrationsmaßnahmen wurde das <strong>Projekt SECESTA ViaSafe: Anwendung des Überwachungsnetzes für die Vulkanascheniederschläge des Ätna zur Verkehrssteuerung im etnäischen Gebiet</strong> gefördert.</p>
            <p style="text-align: justify;">Die häufige explosivtätige Aktivität des Ätna, mit fast 200 dokumentierten Eruptionen in den letzten 30 Jahren, verdeutlicht die Notwendigkeit eines effizienten Monitorings der Emissions-, Transport- und Niederschlagsphänomene von Vulkanasche, um die notwendigen Maßnahmen zur Flugverkehrplanung und zur optimierten Verkehrssteuerung zu organisieren.</p>
            <p style="text-align: justify;">Insbesondere wurde die Installation und experimentelle Validierung eines verteilten Netzes von Sensorknoten im südlichen Teil des Vulkans realisiert, primär zur Sicherstellung des Flughafenbetriebs und zur Sicherheit der Reisenden auf den Autobahnen. Dazu wurden verschiedene Prototypen zur Überwachung des Niederschlags von Vulkanasche entwickelt, basierend auf Einsatz von Bildsensoren sowie auf speziell entwickelten Sensorknoten nach dem für die Prototypen verwendeten Modell. Das verteilte System zur Beobachtung und Messung des Transports und der Niederschläge von Vulkanasche ermöglicht eine Verbesserung des Betriebs des internationalen Flughafens Catania, minimiert die Reinigungszeiten der Landebahnen und Parkflächen und steigert zudem die Sicherheit des ankommenden und abfliegenden Flugverkehrs. Außerdem ermöglicht die Kenntnis der Menge und Eigenschaften der Vulkanasche, die auf urbanes und suburbanes Gebiet niedergeht, eine schnelle und effiziente Entfernung der Vulkanasche von Straßen und befestigten Flächen. Dies führt zu einer signifikanten Verbesserung der Verkehrssicherheit, die das Risiko der Rutschgefahr durch die Anwesenheit von Vulkanpartikeln auf der Fahrbahn reduziert, sowie zur Gesundheit der Bevölkerung in den betroffenen Niederschlagsgebieten, da durch die Zertrümmerung von Asche (Millimeterpartikel) und Lapilli (Zentimeterpartikel) durch Fahrzeuge Feinstaub (PM10 oder kleiner) entsteht. Die Erstellung eines speziellen GIS ermöglichte die Ableitung der Größen zur Berechnung des Volumens und der Art des abgelagerten vulkanischen Materials. Für die Autobahn A18 (Messina - Catania) wurde speziell ein zeitnahes System zur Reduzierung der Höchstgeschwindigkeit von Fahrzeugen entwickelt, basierend auf der während vulkanischer Ereignisse niedergehenden Asche, um die zahlreichen Unfälle der letzten Jahre, darunter auch tödliche, zu vermeiden. Insbesondere werden für jedes eruptive Ereignis die Daten des Vorhersagemodells für die Ascheniederschläge entlang der A18 und des Autobahnzubringers 15 (Tangenziale di Catania) verarbeitet, um Warnmeldungen zu generieren. Die Nachrichten werden automatisch an die Informationssysteme der zuständigen Verwaltungen gesendet, um die Informationen zu verarbeiten und Warnhinweise auf den variable Message Boards entlang der Autobahn zu visualisieren.</p>
            <p style="text-align: justify;">Die mit dem Projekt SECESTA erzielten Ergebnisse bilden eine solide Grundlage für die Entwicklung einer IT-Plattform, die die vom Überwachungssystem für Ascheniederschläge gesammelten Informationen nahezu in Echtzeit nutzt. Die Integration des im Projekt SECESTA entwickelten Messsystems mit weiteren Sensortechnologien, Datenverarbeitungsplattformen und Vorhersagemodellen für den Transport in der Atmosphäre (mittels Algorithmen basierend auf Dispersion- und Wettermodellen, die in Echtzeit mit den erfassten Daten validiert werden) sowie für die Ablagerung von Vulkanasche am Boden, ermöglicht die Entwicklung einer Reihe von Dienstleistungen, um die Mobilität im Ballungsraum Catania effizienter und sicherer zu gestalten, indem ein effektives und zuverlässiges System zur permanenten Überwachung der Vulkanascheniederschläge genutzt wird.</p>
            <p style="text-align: justify;">Dazu wurde in Zusammenarbeit mit einem externen Spezialisten für Sonderabfallentsorgung ein Protokoll zur Wiederverwertung der Asche entwickelt, nachdem sie aus den Straßen der Metropolregion Catania entfernt wurde, was die temporäre Lagerung erleichtert und die Entsorgungskosten für die Verwaltungen und öffentlichen Stellen, die für die Verkehrsinfrastruktur zuständig sind, erheblich reduziert.</p>
            <p style="text-align: justify;">Um die Verbreitung der Informationen über die Ascheniederschläge gegenüber der Bevölkerung zu erleichtern, wurde zudem eine Smartphone-App (EtnaAshApp) entwickelt, die sowohl für Nutzer als auch für zuständige Behörden bestimmt ist, um kontinuierlich über die Ascheniederschläge und die Nutzbarkeit der Straßen informiert zu werden.</p>
            <p style="text-align: justify;">Thematischer Bereich der regionalen Innovationsstrategie für die S3-Spezialisierung und verwendete Technologie: „<strong>Smart Cities & Communities</strong>“, insbesondere im Subbereich „<strong>Smart Mobility</strong>“.</p>
            <p style="text-align: justify;">Das Projektvolumen beträgt <strong>1.922.544,00 €</strong>; die Förderung beträgt <strong>1.525.733,33 €</strong>.</p>
            <p style="text-align: center;"><img src="../images/Gruppo-dei-loghi-Negativo-Colori.png" alt="Gruppo-dei-loghi-Negativo-Colori" class="wp-image-1868" style="width:400px"/></p>
          </div>
        </section>
<?php include '../includes/footer_de.php'; ?>
