<?php 
$path = "../";      // Siamo dentro una cartella, dobbiamo salire di un livello per trovare css e images
$page = "R&I";    // Questo farà illuminare "R&I" nel menu
include '../includes/header_it.php'; // Notare ../ prima di includes
?>
        <section class="inner-hero fade-in">
          <div class="breadcrumb"><a href="../index.php">Home</a> / <a href="ricerca-innovazione.php">Ricerca e Innovazione</a> / 3DLAB Sicilia</div>
          <h1 class="inner-title">3DLAB Sicilia</ISIndex></h1>
        </section>

        <section class="content fade-in">
          <div class="iub_header">
            <p style="text-align: center;"><img src="../images/3DLAB.png" alt="3DLAB" class="wp-image-1868" style="width:400px"/></p>
            <p style="text-align: justify;">Nell’ambito <strong>P.O. FESR SICILIA 2014/2020</strong>, <strong>Obiettivo Tematico 1 – </strong>Ricerca, Sviluppo Tecnologico e Innovazione <strong>Obiettivo specifico 1.1 </strong>- Incremento dell’attività di innovazione delle imprese,<strong> Azione 1.1.5 </strong>- Sostegno all'avanzamento tecnologico delle imprese attraverso il finanziamento di linee pilota e azioni di validazione precoce dei prodotti e di dimostrazione su larga scala è stato finanziato il <strong>Progetto 3DLab - Sicilia - Creazione di una rete regionale per l'erogazione di servizi innovativi basati su tecnologie avanzate di visualizzazione</strong>.</p>
            <p style="text-align: justify;">La disponibilità, sempre crescente e sempre più economica, da un lato di scanner 3D, di sistemi sofisticati di fotogrammetria e di ambienti software sempre più versatili e ricchi di funzionalità e dall'altro di apparecchiature fisse e dispositivi indossabili per la fruizione di ambienti ad alta immersività, ha reso possibile la creazione di un vero e proprio mercato della Realtà Virtuale (VR) e della Realtà Aumentata (AR) che, secondo la Worldwide Semiannual Augmented and Virtual Reality Spending Guide di IDC, prevede un fatturato globale complessivo e una spesa per AR e VR con altissimi tassi di crescita annuale composti e destinato a superare in pochi anni i 150 miliardi di dollari. Applicazioni VR sono sempre più diffuse e numerose in molti campi, quali: medicina, biologia, automotive, manufacturing, beni culturali, pubblica amministrazione, "internet delle cose", architettura, gaming, advertising, vendite online, comunicazione e marketing, turismo, editoria, moda, istruzione, formazione, ecc. ed è estremamente significativa l'emergente integrazione della VR nei processi aziendali come progettazione, produzione, simulazione, manutenzione, sicurezza, ecc. Per tutto quanto ciò, non meraviglia (i) che laboratori VR/AR di visualizzazione avanzata siano in continua creazione e sviluppo, sia in ambiente accademico che industriale, spesso con co-gestione pubblica-privata, e (ii) che recentemente la Commissione Europea abbia finanziato il progetto VISIONAIR che aveva l'obiettivo, conseguito con successo, di creare una rete continentale con più di 20 centri di VR e visualizzazione 3D e di validarla con circa 200 applicazioni e progetti di beni culturali, biologia, chimica, ingegneria, meccatronica, medicina, produzione industriale e molto altro, selezionati mediante procedure competitive.</p>
            <p style="text-align: justify;">3DLab-Sicilia intende da un lato creare e sviluppare e dall'altro validare e promuovere una rete regionale sostenibile di tre (3) centri per la VR/AR e la visualizzazione 3D: uno localizzato nella provincia di Catania (presso SWING:IT), uno a Troina (EN, presso IRCCS-OASI) ed il terzo a Palermo (presso IEMEST). A tale rete, che a nostra conoscenza sarebbe la prima di questa tipologia in Sicilia, è dato il nome convenzionale di "infrastruttura 3DLab-Sicilia". Il progetto altresì valida e dimostra le apparecchiature ed i servizi dell'infrastruttura con una serie di "use case" (alcuni già identificati in fase di preparazione della proposta progettuale e altri individuati durante il progetto per mezzo di selezioni competitive) che intercettano in modo coerente i temi della Smart Specialisation Strategy (S3) della Regione Siciliana e le cui applicazioni e prodotti possono, dopo la fine del progetto, essere "immessi sul mercato" e generare profitto. Ulteriori obiettivi di 3DLab-Sicilia sono quelli di federare l'infrastruttura con quella di VISIONAIR, al fine di creare mercati a livello internazionale, e di definire il modello di gestione, di business e di sostenibilità dell'infrastruttura dopo la fine del progetto. Un elemento saliente del piano di lavoro di 3DLab-Sicilia, che sposa in pieno i concetti di Open Innovation e Open Innovation 2.0, a tripla e "quadrupla elica", è quello di creare all'interno dell'infrastruttura un servizio che mutui il concetto di "liquid lab". I "liquid lab" (noti in ambito industriale come "liquid studios"), sono ambienti sia che reali che virtuali che sfruttano servizi e soluzioni ICT innovativi per aiutare le aziende ad accelerare il loro percorso di innovazione, trasformando velocemente le loro idee in applicazioni e servizi concreti, con l'utilizzo di tecnologie e architetture innovative, intelligent automation e nuove metodologie di sviluppo software. Il "liquid lab" di 3DLab-Sicilia è disegnato e implementato in modo da (i) permettere il rapido sviluppo di applicazioni che usino la VR/AR e la visualizzazione 3D e (ii) fornire supporto a 360 gradi a tutti gli attori della "quadrupla elica" dell'innovazione. Ambito tematico di intervento della Strategia regionale di innovazione per la specializzazione S3 e tecnologia utilizzata: "<strong>Smart Cities &amp; Communities</strong>", in particolare nel sub-ambito "<strong>Smart Economy</strong>".</p>
            <p style="text-align: justify;">L'importo del Progetto è pari a <strong>€3.996.985,59</strong>; l'importo dell'agevolazione è pari a <strong>€3.567.561,18</strong>.</p>
            <p style="text-align: center;"><img src="../images/Gruppo-dei-loghi-Negativo-Colori.png" alt="Gruppo-dei-loghi-Negativo-Colori" class="wp-image-1868" style="width:400px"/></p>
        </div>
        </section>
<?php include '../includes/footer_it.php'; ?>
